#define TOKEN_AND                             1
#define TOKEN_OR                              2
#define TOKEN_EQ                              3
#define TOKEN_NE                              4
#define TOKEN_GT                              5
#define TOKEN_GE                              6
#define TOKEN_LT                              7
#define TOKEN_LE                              8
#define TOKEN_PLUS                            9
#define TOKEN_MINUS                          10
#define TOKEN_TIMES                          11
#define TOKEN_DIVIDE                         12
#define TOKEN_MOD                            13
#define TOKEN_EXP                            14
#define TOKEN_NOT                            15
#define TOKEN_RAW                            16
#define TOKEN_EXPRESSION                     17
#define TOKEN_IF                             18
#define TOKEN_ENDIF                          19
#define TOKEN_ELSE                           20
#define TOKEN_ELSEIF                         21
#define TOKEN_VARIABLE                       22
